import type { ProviderDefinition } from "./types.js";
const api = (
  id: string,
  name: string,
  baseUrl: string,
  docs: string,
  protocol: "openai" | "anthropic" = "openai",
): ProviderDefinition => ({
  id,
  name,
  baseUrl,
  docs,
  protocol,
  category: "api_key",
  auth: "api_key",
  capabilities: { chat: true, code: true },
  adapterStatus: "implemented",
});
const companion = (
  id: string,
  name: string,
  category: "oauth" | "free" | "local" = "oauth",
): ProviderDefinition => ({
  id,
  name,
  category,
  auth: "local_companion",
  capabilities: {},
  adapterStatus: "requires_companion",
});
export const providers: ProviderDefinition[] = [
  companion("claude-code", "Claude Code"),
  companion("codex", "Codex CLI"),
  companion("copilot", "Copilot"),
  companion("cursor", "Cursor"),
  companion("gemini-cli", "Gemini CLI", "free"),
  companion("kiro", "Kiro", "free"),
  companion("qwen-code", "Qwen Code", "free"),
  companion("cline", "Cline", "free"),
  companion("antigravity", "Antigravity", "free"),
  companion("kilo-code", "Kilo Code", "free"),
  api(
    "openai",
    "OpenAI",
    "https://api.openai.com/v1",
    "https://developers.openai.com/api/reference/overview",
  ),
  api(
    "gemini",
    "Gemini",
    "https://generativelanguage.googleapis.com/v1beta/openai",
    "https://ai.google.dev/gemini-api/docs/openai",
  ),
  api(
    "anthropic",
    "Anthropic",
    "https://api.anthropic.com/v1",
    "https://platform.claude.com/docs/en/api/overview",
    "anthropic",
  ),
  api(
    "openrouter",
    "OpenRouter",
    "https://openrouter.ai/api/v1",
    "https://openrouter.ai/docs/api_reference/overview",
  ),
  api(
    "groq",
    "Groq",
    "https://api.groq.com/openai/v1",
    "https://console.groq.com/docs/openai",
  ),
  api(
    "deepseek",
    "DeepSeek",
    "https://api.deepseek.com/v1",
    "https://api-docs.deepseek.com/api/list-models/",
  ),
  api(
    "mistral",
    "Mistral",
    "https://api.mistral.ai/v1",
    "https://docs.mistral.ai/api",
  ),
  api(
    "together",
    "Together AI",
    "https://api.together.xyz/v1",
    "https://docs.together.ai/docs/inference/openai-compatibility",
  ),
  api(
    "fireworks",
    "Fireworks AI",
    "https://api.fireworks.ai/inference/v1",
    "https://docs.fireworks.ai/tools-sdks/openai-compatibility",
  ),
  api(
    "cerebras",
    "Cerebras",
    "https://api.cerebras.ai/v1",
    "https://inference-docs.cerebras.ai/resources/openai",
  ),
  api(
    "xai",
    "xAI",
    "https://api.x.ai/v1",
    "https://docs.x.ai/developers/rest-api-reference/inference/chat-completions",
  ),
  {
    id: "openai-compatible",
    name: "OpenAI Compatible",
    category: "compatible",
    auth: "custom",
    capabilities: { chat: true, code: true },
    adapterStatus: "implemented",
    protocol: "openai",
  },
  {
    id: "anthropic-compatible",
    name: "Anthropic Compatible",
    category: "compatible",
    auth: "custom",
    capabilities: { chat: true, code: true },
    adapterStatus: "implemented",
    protocol: "anthropic",
  },
  {
    id: "custom-rest",
    name: "Custom REST",
    category: "compatible",
    auth: "custom",
    capabilities: {},
    adapterStatus: "unsupported",
  },
  companion("ollama", "Ollama", "local"),
];
export const providerById = (id: string) => providers.find((p) => p.id === id);
export const virtualModels = [
  "auto",
  "auto/balanced",
  "auto/fast",
  "auto/cheap",
  "auto/quality",
];
